list = [
  {client: "Alliance", name: "Badger"},
  {client: "Alliance", name: "Charleston"},
  {client: "Alliance", name: "Houma"},
  {client: "Alliance", name: "Houston"},
  {client: "Alliance", name: "Ms Taylor"},
  {client: "Alliance", name: "Nashville"},
  {client: "Aries", name: "Ram XIV"},
  {client: "Aries", name: "Ram XIX"},
  {client: "Baker", name: "Special"},
  {client: "ECO", name: "Holiday"},
  {client: "ECO", name: "Norbert Bouziga"},
  {client: "ECO", name: "Springbok"},
  {client: "FG", name: "LB Kayd"},
  {client: "FG", name: "Seacor Influence"},
  {client: "FG", name: "Seacor Power"},
  {client: "FG", name: "Seacor Eagle"},
  {client: "Seacor", name: "Endeavor"},
  {client: "Seacor", name: "Hawk"},
  {client: "Harvey", name: "Hurricane"},
  {client: "Harvey", name: "Pioneer"},
  {client: "Harvey", name: "Rain"},
  {client: "Harvey", name: "Supporter"},
  {client: "Harvey", name: "Wave"},
  {client: "HOS", name: "Blackrock"},
  {client: "HOS", name: "Blackwatch"},
  {client: "HOS", name: "Carousel"},
  {client: "HOS", name: "Clearview"},
  {client: "HOS", name: "Crockett"},
  {client: "Kilgore", name: "K-Marine XXII"},
  {client: "Kilgore", name: "K-Marine VII"},
  {client: "Kilgore", name: "K-Marine VI"},
  {client: "Kinetica", name: "VRM 397 rotation"},
  {client: "Laborde", name: "Genie Lab"},
  {client: "Laborde", name: "Persistance Lab"},
  {client: "Laredo", name: "Brazos"},
  {client: "Laredo", name: "Petite"},
  {client: "Laredo", name: "Trinity"},
  {client: "SeaTran", name: "Greater Scott"},
  {client: "SeaTran", name: "Lady Eve"},
  {client: "Triton", name: "Crusader"},
  {client: "TDW", name: "Southern Tide"},
  {client: "TDW", name: "Terrel Tide"},
  {client: "TDW", name: "Youngs Tide"},
  {client: "Triton", name: "Patriot"},
  {client: "Alliance", name: "Andi Nicol"},
  {client: "ECO", name: "Kirt Chouest"},
  {client: "ECO", name: "Ms Charlotte Chouest"}
]

list.each do |atts|
  Project.create!(atts)
end
