Position.where(name: 'Rigger').update_all(color: "#808000")
Position.where(name: 'Cook').update_all(color: "#911EB4")
Position.where(name: 'Galley Hand').update_all(color: "#E6BEFF")
Position.where(name: 'Solids Control Tech').update_all(color: "#9A6324")
Position.where(name: 'Steward').update_all(color: "#469990")
Position.where(name: 'Filtration Tech').update_all(color: "#BFEF45")
Position.where(name: 'Drilling Fluids Engineer').update_all(color: "#3CB44B")
Position.where(name: 'Completion Fluids Engineer').update_all(color: "#469990")
Position.where(name: 'Blue Fin').update_all(color: "#4363D8")
Position.where(name: 'Diver').update_all(color: "#000075")
Position.where(name: 'Forklift Operator').update_all(color: "#AAFFC3")
Position.where(name: 'Mud Engineer').update_all(color: "#000000")
Position.where(name: 'Dispatcher').update_all(color: "#FFFFFF")
Position.where(name: 'Hydro Tester').update_all(color: "#FFE119")
Position.where(name: 'Operator').update_all(color: "#F58231")
Position.where(name: 'Rig Clerk').update_all(color: "#42D4F4")
Position.where(name: 'Crane Operator').update_all(color: "#F032E6")
Position.where(name: 'General Labor').update_all(color: "#FABEBE")
